_target_: unhippo.models.ssms.UnLSSL

name: ???

n_layers: 6
in_channels: ${data.n_features}
out_channels: ${oc.select:data.n_classes,${oc.select:data.n_targets,""}}
hidden_channels: 128
n: 128
trainable: ???
n_latent_channels: 1
obs_sigma2: 1.0
trans_sigma2: 1.0
symmetrize: True
joseph: True
krylov: True
# As in the LSSL paper
min_t: 10
max_t: 1000
discretization_method: expm
dropout: 0.01
